FROM node:16.18.1

WORKDIR /app

COPY . .

ENV PORT=8000 \
    DB_FILE=db/dev.db \
    JWT_SECRET=2yaxLzK187etZw \
    JWT_EXPIRES_IN=604800 \
    SCHEMA=bnb_schema


RUN npm install

RUN npm run sequelize --prefix backend db:migrate && npm run sequelize --prefix backend db:seed:all

EXPOSE 8000

CMD ["npm", "start"]
